### ISSUE TITLE
I can't figure it out...

### ISSUE THREAD

**Issue by Connor03** [ASHTeam/Splatoon-Static.pack-Dumper#1]
it says on the instructions to put your computer IP into your Wii U, but I don't know where and how to do it. Please respond if you have a solution. Thanks :)

**Comment by v1tal** [comment]
this isnt an issue lol

**Comment by Connor03** [comment]
Well then please tell me why I won't connect to the internet whenever I put
in a new ip

**Comment by Hexexpeck** [comment]
This version is buggy hence the reason I deleted the source, I am working on a better and improved version. Please refrain from using this version until the new one is released.
